# Generated by Django 4.2.16 on 2024-11-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_product_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="care_instructions",
            field=models.TextField(default="Dry clean only"),
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
