# Generated by Django 5.0 on 2024-11-03 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_care_instructions_product_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Collection',
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('name',), 'verbose_name': 'collection', 'verbose_name_plural': 'collections'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='collection',
        ),
        migrations.RenameField(
            model_name='suit',
            old_name='category',
            new_name='collection',
        ),
    ]
